### ISSUE TITLE
Proof reading lin reg chapter

### ISSUE THREAD

**Issue by simonthelwall** [UCL-ARC/r-amr-epidemiology#27]
### description

I've had a quick scan of the linear regression chapter and spotted some typos. I've listed what I've spotted below but also I could edit and submit a pull request if that would help?

**Log transform**
- "If your data is skwewed, ..."
- 3rd para: "If the dependent/response variable is solely log-transformed. Exponentiate the coefficient." suggest comma, rather than full stop and capital.
- 4th para: "If both are transformed. nterpret ..." should be "If both are transformed, interpret "

**Broom**
 -  2nd para: The list formatting has failed, and what should be bullet points render as asterisks
 
**t-test**
 - para 5, list formatting has failed as above

**Conventions**
 - list formatting has failed as above

**Comment by quirksahern** [comment]
@simonthelwall yes, please.
