### ISSUE TITLE
Customise Git example to context

### ISSUE THREAD

**Issue by quirksahern** [UCL-ARC/r-amr-epidemiology#4]
Update Git lessons episodes 8, 9 and 10 to build a data dictionary. Replacing wolfman and dracula examples. Could be based upon an existing data dictionary, either for UKHSA provided data or the IMD dimensions data

**Comment by milanmlft** [comment]
Should episode 11 ("Exploring History") also be updated?

**Comment by quirksahern** [comment]
Yes, re: episode 11

We can base the examples on the attached data dictionary, they'll be using this data for the logistic regression
[amr_data_dictionary.md](https://github.com/user-attachments/files/16598349/amr_data_dictionary.md)
