### ISSUE TITLE
New episode: Reporting with Quarto

### ISSUE THREAD

**Issue by quirksahern** [UCL-ARC/r-amr-epidemiology#5]
Replace markdown session with Quarto material, update example exercise to use the London IMD dimensions data.
Request to include parametisation in reports.

Possible material to use/ take inspirisation dfrom: https://dept.stat.lsa.umich.edu/~jerrick/courses/stat506/02-rmarkdown.html

**Comment by milanmlft** [comment]
Use [A step-by-step guide to parameterized reporting in R using Quarto - R for the Rest of Us](https://rfortherestofus.com/2024/06/parameterized-reporting-quarto) as example for parametrised reports
